language: python
sudo: false
python:
  - "3.4"
  - "nightly"

matrix:
  allow_failures:
    - python: nightly

install:
  - pip install -r requirements.txt
  - pip install flake8

before_script: flake8
script: nosetests
